version: "3.2"

services:
  elasticsearch:
    build: ./elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
      - ./elasticsearch/lib:/var/lib/elasticsearch
      - ./elasticsearch/log:/var/log/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      elasticsearch:
        ipv4_address: 10.0.0.20
    environment:
      - discovery.type=single-node
  
  logstash:
    build: ./logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/lib:/var/lib/logstash
      - ./logstash/log:/var/log/logstash
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      elasticsearch:
        ipv4_address: 10.0.0.10
    depends_on:
      - elasticsearch
      - kibana

  kibana:
    build: ./kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/lib:/var/lib/kibana
      - ./kibana/log:/var/log/kibana
    ports:
      - "5601:5601"
    networks:
      elasticsearch:
        ipv4_address: 10.0.0.30
    depends_on:
      - elasticsearch

networks:
  elasticsearch:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
